In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier#回归
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
%matplotlib inline
from sklearn import datasets
import pandas as pd
from sklearn.linear_model import LogisticRegression#导入逻辑回归包

In [2]:
path=r"C:\Users\xuhao_yang\PycharmProjects\data\adults.txt"

In [3]:
data=pd.read_csv(path)
data

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>age</th>
      <th>workclass</th>
      <th>final_weight</th>
      <th>education</th>
      <th>education_num</th>
      <th>marital_status</th>
      <th>occupation</th>
      <th>relationship</th>
      <th>race</th>
      <th>sex</th>
      <th>capital_gain</th>
      <th>capital_loss</th>
      <th>hours_per_week</th>
      <th>native_country</th>
      <th>salary</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>39</td>
      <td>State-gov</td>
      <td>77516</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Never-married</td>
      <td>Adm-clerical</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Male</td>
      <td>2174</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>1</th>
      <td>50</td>
      <td>Self-emp-not-inc</td>
      <td>83311</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Married-civ-spouse</td>
      <td>Exec-managerial</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>13</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>2</th>
      <td>38</td>
      <td>Private</td>
      <td>215646</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Divorced</td>
      <td>Handlers-cleaners</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>3</th>
      <td>53</td>
      <td>Private</td>
      <td>234721</td>
      <td>11th</td>
      <td>7</td>
      <td>Married-civ-spouse</td>
      <td>Handlers-cleaners</td>
      <td>Husband</td>
      <td>Black</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>4</th>
      <td>28</td>
      <td>Private</td>
      <td>338409</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Married-civ-spouse</td>
      <td>Prof-specialty</td>
      <td>Wife</td>
      <td>Black</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>Cuba</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>5</th>
      <td>37</td>
      <td>Private</td>
      <td>284582</td>
      <td>Masters</td>
      <td>14</td>
      <td>Married-civ-spouse</td>
      <td>Exec-managerial</td>
      <td>Wife</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>6</th>
      <td>49</td>
      <td>Private</td>
      <td>160187</td>
      <td>9th</td>
      <td>5</td>
      <td>Married-spouse-absent</td>
      <td>Other-service</td>
      <td>Not-in-family</td>
      <td>Black</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>16</td>
      <td>Jamaica</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>7</th>
      <td>52</td>
      <td>Self-emp-not-inc</td>
      <td>209642</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Married-civ-spouse</td>
      <td>Exec-managerial</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>45</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>8</th>
      <td>31</td>
      <td>Private</td>
      <td>45781</td>
      <td>Masters</td>
      <td>14</td>
      <td>Never-married</td>
      <td>Prof-specialty</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Female</td>
      <td>14084</td>
      <td>0</td>
      <td>50</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>9</th>
      <td>42</td>
      <td>Private</td>
      <td>159449</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Married-civ-spouse</td>
      <td>Exec-managerial</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>5178</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>10</th>
      <td>37</td>
      <td>Private</td>
      <td>280464</td>
      <td>Some-college</td>
      <td>10</td>
      <td>Married-civ-spouse</td>
      <td>Exec-managerial</td>
      <td>Husband</td>
      <td>Black</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>80</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>11</th>
      <td>30</td>
      <td>State-gov</td>
      <td>141297</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Married-civ-spouse</td>
      <td>Prof-specialty</td>
      <td>Husband</td>
      <td>Asian-Pac-Islander</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>India</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>12</th>
      <td>23</td>
      <td>Private</td>
      <td>122272</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Never-married</td>
      <td>Adm-clerical</td>
      <td>Own-child</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>30</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>13</th>
      <td>32</td>
      <td>Private</td>
      <td>205019</td>
      <td>Assoc-acdm</td>
      <td>12</td>
      <td>Never-married</td>
      <td>Sales</td>
      <td>Not-in-family</td>
      <td>Black</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>50</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>14</th>
      <td>40</td>
      <td>Private</td>
      <td>121772</td>
      <td>Assoc-voc</td>
      <td>11</td>
      <td>Married-civ-spouse</td>
      <td>Craft-repair</td>
      <td>Husband</td>
      <td>Asian-Pac-Islander</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>?</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>15</th>
      <td>34</td>
      <td>Private</td>
      <td>245487</td>
      <td>7th-8th</td>
      <td>4</td>
      <td>Married-civ-spouse</td>
      <td>Transport-moving</td>
      <td>Husband</td>
      <td>Amer-Indian-Eskimo</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>45</td>
      <td>Mexico</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>16</th>
      <td>25</td>
      <td>Self-emp-not-inc</td>
      <td>176756</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Never-married</td>
      <td>Farming-fishing</td>
      <td>Own-child</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>35</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>17</th>
      <td>32</td>
      <td>Private</td>
      <td>186824</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Never-married</td>
      <td>Machine-op-inspct</td>
      <td>Unmarried</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>18</th>
      <td>38</td>
      <td>Private</td>
      <td>28887</td>
      <td>11th</td>
      <td>7</td>
      <td>Married-civ-spouse</td>
      <td>Sales</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>50</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>19</th>
      <td>43</td>
      <td>Self-emp-not-inc</td>
      <td>292175</td>
      <td>Masters</td>
      <td>14</td>
      <td>Divorced</td>
      <td>Exec-managerial</td>
      <td>Unmarried</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>45</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>20</th>
      <td>40</td>
      <td>Private</td>
      <td>193524</td>
      <td>Doctorate</td>
      <td>16</td>
      <td>Married-civ-spouse</td>
      <td>Prof-specialty</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>60</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>21</th>
      <td>54</td>
      <td>Private</td>
      <td>302146</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Separated</td>
      <td>Other-service</td>
      <td>Unmarried</td>
      <td>Black</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>20</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>22</th>
      <td>35</td>
      <td>Federal-gov</td>
      <td>76845</td>
      <td>9th</td>
      <td>5</td>
      <td>Married-civ-spouse</td>
      <td>Farming-fishing</td>
      <td>Husband</td>
      <td>Black</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>23</th>
      <td>43</td>
      <td>Private</td>
      <td>117037</td>
      <td>11th</td>
      <td>7</td>
      <td>Married-civ-spouse</td>
      <td>Transport-moving</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>2042</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>24</th>
      <td>59</td>
      <td>Private</td>
      <td>109015</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Divorced</td>
      <td>Tech-support</td>
      <td>Unmarried</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>25</th>
      <td>56</td>
      <td>Local-gov</td>
      <td>216851</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Married-civ-spouse</td>
      <td>Tech-support</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>26</th>
      <td>19</td>
      <td>Private</td>
      <td>168294</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Never-married</td>
      <td>Craft-repair</td>
      <td>Own-child</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>27</th>
      <td>54</td>
      <td>?</td>
      <td>180211</td>
      <td>Some-college</td>
      <td>10</td>
      <td>Married-civ-spouse</td>
      <td>?</td>
      <td>Husband</td>
      <td>Asian-Pac-Islander</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>60</td>
      <td>South</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>28</th>
      <td>39</td>
      <td>Private</td>
      <td>367260</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Divorced</td>
      <td>Exec-managerial</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>80</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>29</th>
      <td>49</td>
      <td>Private</td>
      <td>193366</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Married-civ-spouse</td>
      <td>Craft-repair</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>32531</th>
      <td>30</td>
      <td>?</td>
      <td>33811</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Never-married</td>
      <td>?</td>
      <td>Not-in-family</td>
      <td>Asian-Pac-Islander</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>99</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32532</th>
      <td>34</td>
      <td>Private</td>
      <td>204461</td>
      <td>Doctorate</td>
      <td>16</td>
      <td>Married-civ-spouse</td>
      <td>Prof-specialty</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>60</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32533</th>
      <td>54</td>
      <td>Private</td>
      <td>337992</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Married-civ-spouse</td>
      <td>Exec-managerial</td>
      <td>Husband</td>
      <td>Asian-Pac-Islander</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>50</td>
      <td>Japan</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32534</th>
      <td>37</td>
      <td>Private</td>
      <td>179137</td>
      <td>Some-college</td>
      <td>10</td>
      <td>Divorced</td>
      <td>Adm-clerical</td>
      <td>Unmarried</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>39</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32535</th>
      <td>22</td>
      <td>Private</td>
      <td>325033</td>
      <td>12th</td>
      <td>8</td>
      <td>Never-married</td>
      <td>Protective-serv</td>
      <td>Own-child</td>
      <td>Black</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>35</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32536</th>
      <td>34</td>
      <td>Private</td>
      <td>160216</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Never-married</td>
      <td>Exec-managerial</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>55</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32537</th>
      <td>30</td>
      <td>Private</td>
      <td>345898</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Never-married</td>
      <td>Craft-repair</td>
      <td>Not-in-family</td>
      <td>Black</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>46</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32538</th>
      <td>38</td>
      <td>Private</td>
      <td>139180</td>
      <td>Bachelors</td>
      <td>13</td>
      <td>Divorced</td>
      <td>Prof-specialty</td>
      <td>Unmarried</td>
      <td>Black</td>
      <td>Female</td>
      <td>15020</td>
      <td>0</td>
      <td>45</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32539</th>
      <td>71</td>
      <td>?</td>
      <td>287372</td>
      <td>Doctorate</td>
      <td>16</td>
      <td>Married-civ-spouse</td>
      <td>?</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>10</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32540</th>
      <td>45</td>
      <td>State-gov</td>
      <td>252208</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Separated</td>
      <td>Adm-clerical</td>
      <td>Own-child</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32541</th>
      <td>41</td>
      <td>?</td>
      <td>202822</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Separated</td>
      <td>?</td>
      <td>Not-in-family</td>
      <td>Black</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>32</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32542</th>
      <td>72</td>
      <td>?</td>
      <td>129912</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Married-civ-spouse</td>
      <td>?</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>25</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32543</th>
      <td>45</td>
      <td>Local-gov</td>
      <td>119199</td>
      <td>Assoc-acdm</td>
      <td>12</td>
      <td>Divorced</td>
      <td>Prof-specialty</td>
      <td>Unmarried</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>48</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32544</th>
      <td>31</td>
      <td>Private</td>
      <td>199655</td>
      <td>Masters</td>
      <td>14</td>
      <td>Divorced</td>
      <td>Other-service</td>
      <td>Not-in-family</td>
      <td>Other</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>30</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32545</th>
      <td>39</td>
      <td>Local-gov</td>
      <td>111499</td>
      <td>Assoc-acdm</td>
      <td>12</td>
      <td>Married-civ-spouse</td>
      <td>Adm-clerical</td>
      <td>Wife</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>20</td>
      <td>United-States</td>
      <td>&gt;50K</td>
    </tr>
    <tr>
      <th>32546</th>
      <td>37</td>
      <td>Private</td>
      <td>198216</td>
      <td>Assoc-acdm</td>
      <td>12</td>
      <td>Divorced</td>
      <td>Tech-support</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32547</th>
      <td>43</td>
      <td>Private</td>
      <td>260761</td>
      <td>HS-grad</td>
      <td>9</td>
      <td>Married-civ-spouse</td>
      <td>Machine-op-inspct</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>Mexico</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32548</th>
      <td>65</td>
      <td>Self-emp-not-inc</td>
      <td>99359</td>
      <td>Prof-school</td>
      <td>15</td>
      <td>Never-married</td>
      <td>Prof-specialty</td>
      <td>Not-in-family</td>
      <td>White</td>
      <td>Male</td>
      <td>1086</td>
      <td>0</td>
      <td>60</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32549</th>
      <td>43</td>
      <td>State-gov</td>
      <td>255835</td>
      <td>Some-college</td>
      <td>10</td>
      <td>Divorced</td>
      <td>Adm-clerical</td>
      <td>Other-relative</td>
      <td>White</td>
      <td>Female</td>
      <td>0</td>
      <td>0</td>
      <td>40</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32550</th>
      <td>43</td>
      <td>Self-emp-not-inc</td>
      <td>27242</td>
      <td>Some-college</td>
      <td>10</td>
      <td>Married-civ-spouse</td>
      <td>Craft-repair</td>
      <td>Husband</td>
      <td>White</td>
      <td>Male</td>
      <td>0</td>
      <td>0</td>
      <td>50</td>
      <td>United-States</td>
      <td>&lt;=50K</td>
    </tr>
    <tr>
      <th>32551</th>
      <td>32</td>
      <td>Private</td>
      <td>34066</td>
      <td>10th</td>
      <td>6</td>
      <td>Married-civ-spouse</td>
      <td>Handlers-cleaners</td>
      <td>Husband</td>

In [4]:
data.columns

Index(['age', 'workclass', 'final_weight', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'salary'],
      dtype='object')

In [5]:
X=data[['age','education','occupation','hours_per_week']]
X

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>age</th>
      <th>education</th>
      <th>occupation</th>
      <th>hours_per_week</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>39</td>
      <td>Bachelors</td>
      <td>Adm-clerical</td>
      <td>40</td>
    </tr>
    <tr>
      <th>1</th>
      <td>50</td>
      <td>Bachelors</td>
      <td>Exec-managerial</td>
      <td>13</td>
    </tr>
    <tr>
      <th>2</th>
      <td>38</td>
      <td>HS-grad</td>
      <td>Handlers-cleaners</td>
      <td>40</td>
    </tr>
    <tr>
      <th>3</th>
      <td>53</td>
      <td>11th</td>
      <td>Handlers-cleaners</td>
      <td>40</td>
    </tr>
    <tr>
      <th>4</th>
      <td>28</td>
      <td>Bachelors</td>
      <td>Prof-specialty</td>
      <td>40</td>
    </tr>
    <tr>
      <th>5</th>
      <td>37</td>
      <td>Masters</td>
      <td>Exec-managerial</td>
      <td>40</td>
    </tr>
    <tr>
      <th>6</th>
      <td>49</td>
      <td>9th</td>
      <td>Other-service</td>
      <td>16</td>
    </tr>
    <tr>
      <th>7</th>
      <td>52</td>
      <td>HS-grad</td>
      <td>Exec-managerial</td>
      <td>45</td>
    </tr>
    <tr>
      <th>8</th>
      <td>31</td>
      <td>Masters</td>
      <td>Prof-specialty</td>
      <td>50</td>
    </tr>
    <tr>
      <th>9</th>
      <td>42</td>
      <td>Bachelors</td>
      <td>Exec-managerial</td>
      <td>40</td>
    </tr>
    <tr>
      <th>10</th>
      <td>37</td>
      <td>Some-college</td>
      <td>Exec-managerial</td>
      <td>80</td>
    </tr>
    <tr>
      <th>11</th>
      <td>30</td>
      <td>Bachelors</td>
      <td>Prof-specialty</td>
      <td>40</td>
    </tr>
    <tr>
      <th>12</th>
      <td>23</td>
      <td>Bachelors</td>
      <td>Adm-clerical</td>
      <td>30</td>
    </tr>
    <tr>
      <th>13</th>
      <td>32</td>
      <td>Assoc-acdm</td>
      <td>Sales</td>
      <td>50</td>
    </tr>
    <tr>
      <th>14</th>
      <td>40</td>
      <td>Assoc-voc</td>
      <td>Craft-repair</td>
      <td>40</td>
    </tr>
    <tr>
      <th>15</th>
      <td>34</td>
      <td>7th-8th</td>
      <td>Transport-moving</td>
      <td>45</td>
    </tr>
    <tr>
      <th>16</th>
      <td>25</td>
      <td>HS-grad</td>
      <td>Farming-fishing</td>
      <td>35</td>
    </tr>
    <tr>
      <th>17</th>
      <td>32</td>
      <td>HS-grad</td>
      <td>Machine-op-inspct</td>
      <td>40</td>
    </tr>
    <tr>
      <th>18</th>
      <td>38</td>
      <td>11th</td>
      <td>Sales</td>
      <td>50</td>
    </tr>
    <tr>
      <th>19</th>
      <td>43</td>
      <td>Masters</td>
      <td>Exec-managerial</td>
      <td>45</td>
    </tr>
    <tr>
      <th>20</th>
      <td>40</td>
      <td>Doctorate</td>
      <td>Prof-specialty</td>
      <td>60</td>
    </tr>
    <tr>
      <th>21</th>
      <td>54</td>
      <td>HS-grad</td>
      <td>Other-service</td>
      <td>20</td>
    </tr>
    <tr>
      <th>22</th>
      <td>35</td>
      <td>9th</td>
      <td>Farming-fishing</td>
      <td>40</td>
    </tr>
    <tr>
      <th>23</th>
      <td>43</td>
      <td>11th</td>
      <td>Transport-moving</td>
      <td>40</td>
    </tr>
    <tr>
      <th>24</th>
      <td>59</td>
      <td>HS-grad</td>
      <td>Tech-support</td>
      <td>40</td>
    </tr>
    <tr>
      <th>25</th>
      <td>56</td>
      <td>Bachelors</td>
      <td>Tech-support</td>
      <td>40</td>
    </tr>
    <tr>
      <th>26</th>
      <td>19</td>
      <td>HS-grad</td>
      <td>Craft-repair</td>
      <td>40</td>
    </tr>
    <tr>
      <th>27</th>
      <td>54</td>
      <td>Some-college</td>
      <td>?</td>
      <td>60</td>
    </tr>
    <tr>
      <th>28</th>
      <td>39</td>
      <td>HS-grad</td>
      <td>Exec-managerial</td>
      <td>80</td>
    </tr>
    <tr>
      <th>29</th>
      <td>49</td>
      <td>HS-grad</td>
      <td>Craft-repair</td>
      <td>40</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>32531</th>
      <td>30</td>
      <td>Bachelors</td>
      <td>?</td>
      <td>99</td>
    </tr>
    <tr>
      <th>32532</th>
      <td>34</td>
      <td>Doctorate</td>
      <td>Prof-specialty</td>
      <td>60</td>
    </tr>
    <tr>
      <th>32533</th>
      <td>54</td>
      <td>Bachelors</td>
      <td>Exec-managerial</td>
      <td>50</td>
    </tr>
    <tr>
      <th>32534</th>
      <td>37</td>
      <td>Some-college</td>
      <td>Adm-clerical</td>
      <td>39</td>
    </tr>
    <tr>
      <th>32535</th>
      <td>22</td>
      <td>12th</td>
      <td>Protective-serv</td>
      <td>35</td>
    </tr>
    <tr>
      <th>32536</th>
      <td>34</td>
      <td>Bachelors</td>
      <td>Exec-managerial</td>
      <td>55</td>
    </tr>
    <tr>
      <th>32537</th>
      <td>30</td>
      <td>HS-grad</td>
      <td>Craft-repair</td>
      <td>46</td>
    </tr>
    <tr>
      <th>32538</th>
      <td>38</td>
      <td>Bachelors</td>
      <td>Prof-specialty</td>
      <td>45</td>
    </tr>
    <tr>
      <th>32539</th>
      <td>71</td>
      <td>Doctorate</td>
      <td>?</td>
      <td>10</td>
    </tr>
    <tr>
      <th>32540</th>
      <td>45</td>
      <td>HS-grad</td>
      <td>Adm-clerical</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32541</th>
      <td>41</td>
      <td>HS-grad</td>
      <td>?</td>
      <td>32</td>
    </tr>
    <tr>
      <th>32542</th>
      <td>72</td>
      <td>HS-grad</td>
      <td>?</td>
      <td>25</td>
    </tr>
    <tr>
      <th>32543</th>
      <td>45</td>
      <td>Assoc-acdm</td>
      <td>Prof-specialty</td>
      <td>48</td>
    </tr>
    <tr>
      <th>32544</th>
      <td>31</td>
      <td>Masters</td>
      <td>Other-service</td>
      <td>30</td>
    </tr>
    <tr>
      <th>32545</th>
      <td>39</td>
      <td>Assoc-acdm</td>
      <td>Adm-clerical</td>
      <td>20</td>
    </tr>
    <tr>
      <th>32546</th>
      <td>37</td>
      <td>Assoc-acdm</td>
      <td>Tech-support</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32547</th>
      <td>43</td>
      <td>HS-grad</td>
      <td>Machine-op-inspct</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32548</th>
      <td>65</td>
      <td>Prof-school</td>
      <td>Prof-specialty</td>
      <td>60</td>
    </tr>
    <tr>
      <th>32549</th>
      <td>43</td>
      <td>Some-college</td>
      <td>Adm-clerical</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32550</th>
      <td>43</td>
      <td>Some-college</td>
      <td>Craft-repair</td>
      <td>50</td>
    </tr>
    <tr>
      <th>32551</th>
      <td>32</td>
      <td>10th</td>
      <td>Handlers-cleaners</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32552</th>
      <td>43</td>
      <td>Assoc-voc</td>
      <td>Sales</td>
      <td>45</td>
    </tr>
    <tr>
      <th>32553</th>
      <td>32</td>
      <td>Masters</td>
      <td>Tech-support</td>
      <td>11</td>
    </tr>
    <tr>
      <th>32554</th>
      <td>53</td>
      <td>Masters</td>
      <td>Exec-managerial</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32555</th>
      <td>22</td>
      <td>Some-college</td>
      <td>Protective-serv</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32556</th>
      <td>27</td>
      <td>Assoc-acdm</td>
      <td>Tech-support</td>
      <td>38</td>
    </tr>
    <tr>
      <th>32557</th>
      <td>40</td>
      <td>HS-grad</td>
      <td>Machine-op-inspct</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32558</th>
      <td>58</td>
      <td>HS-grad</td>
      <td>Adm-clerical</td>
      <td>40</td>
    </tr>
    <tr>
      <th>32559</th>
      <td>22</td>
      <td>HS-grad</td>
      <td>Adm-clerical</td>
      <td>20</td>
    </tr>
    <tr>
      <th>32560</th>
      <td>52</td>
      <td>HS-grad</td>
      <td>Exec-managerial</td>
      <td>40</td>
    </tr>
  </tbody>
</table>
<p>32561 rows × 4 columns</p>
</div>

In [6]:
Y=data['salary']
Y

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
5        <=50K
6        <=50K
7         >50K
8         >50K
9         >50K
10        >50K
11        >50K
12       <=50K
13       <=50K
14        >50K
15       <=50K
16       <=50K
17       <=50K
18       <=50K
19        >50K
20        >50K
21       <=50K
22       <=50K
23       <=50K
24       <=50K
25        >50K
26       <=50K
27        >50K
28       <=50K
29       <=50K
         ...
32531    <=50K
32532     >50K
32533     >50K
32534    <=50K
32535    <=50K
32536     >50K
32537    <=50K
32538     >50K
32539     >50K
32540    <=50K
32541    <=50K
32542    <=50K
32543    <=50K
32544    <=50K
32545     >50K
32546    <=50K
32547    <=50K
32548    <=50K
32549    <=50K
32550    <=50K
32551    <=50K
32552    <=50K
32553    <=50K
32554     >50K
32555    <=50K
32556    <=50K
32557     >50K
32558    <=50K
32559    <=50K
32560     >50K
Name: salary, Length: 32561, dtype: object

In [7]:
X["education"].unique().size

16

In [8]:
X["education"].unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [9]:
X["occupation"].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [10]:
def edu2float(edu):#把学历进行量化
    return np.argwhere(X["education"].unique()==edu)[0,0]

In [11]:
def occupation2float(occupation):#把职业进行量化
    return np.argwhere(X["occupation"].unique()==occupation)[0,0]

In [13]:
X["occupation"]=X["occupation"].map(occupation2float)
X["education"]=X["education"].map(edu2float)

C:\Users\xuhao_yang\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

C:\Users\xuhao_yang\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [15]:
X_train=X.iloc[:-1000]#训练数据
X_test=X.iloc[-1000:]#测试数据
Y_train=Y.iloc[:-1000]
Y_test=Y.iloc[-1000:]

In [17]:
logic=LogisticRegression(solver='liblinear',multi_class='auto')
logic.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='auto',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
Ynew=logic.predict(X_test)

In [19]:
result=(Y_test==Ynew)
accuracy=result.sum()/1000

In [20]:
accuracy

0.739